<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="executionplan" nsURI="http://iobserve.org/ExecutionPlan" nsPrefix="org.iobserve">
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyContextAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetAllocationContext"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceContainerAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetResourceContainer"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeployComponentAction" eSuperTypes="#//AssemblyContextAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="UndeployComponentAction" eSuperTypes="#//AssemblyContextAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="MigrateComponentStateAction" eSuperTypes="#//AssemblyContextAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAllocationContext"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectComponentAction" eSuperTypes="#//AssemblyContextAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetConnectors" upperBound="-1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyConnector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockRequestsToComponentAction" eSuperTypes="#//AssemblyContextAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="DisconnectComponentAction" eSuperTypes="#//AssemblyContextAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetConnectors" upperBound="-1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyConnector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinishComponentAction" eSuperTypes="#//AssemblyContextAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="AllocateNodeAction" eSuperTypes="#//ResourceContainerAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeallocateNodeAction" eSuperTypes="#//ResourceContainerAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectNodeAction" eSuperTypes="#//ResourceContainerAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetConnectors" upperBound="-1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/LinkingResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisconnectNodeAction" eSuperTypes="#//ResourceContainerAction"/>
</ecore:EPackage>
