<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="systemadaptation" nsURI="http://iobserve.org/SystemAdaptation"
    nsPrefix="org.iobserve">
  <eClassifiers xsi:type="ecore:EClass" name="SystemAdaptation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceContainer" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyContextAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAssemblyContext"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceContainerAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceResourceContainer"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeRepositoryComponentAction" eSuperTypes="#//AssemblyContextAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newRepositoryComponent"
        ordered="false" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/RepositoryComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllocateAction" eSuperTypes="#//AssemblyContextAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newAllocationContext" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeallocateAction" eSuperTypes="#//AssemblyContextAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="MigrateAction" eSuperTypes="#//AssemblyContextAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newAllocationContext" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAllocationContext"
        lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AcquireAction" eSuperTypes="#//ResourceContainerAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="TerminateAction" eSuperTypes="#//ResourceContainerAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReplicateAction" eSuperTypes="#//ResourceContainerAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newResourceContainer" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAllocationContext"
        lowerBound="1" upperBound="-1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newAllocationContext" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
  </eClassifiers>
</ecore:EPackage>
