<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="systemadaptation" nsURI="http://iobserve.org/SystemAdaptation"
    nsPrefix="org.iobserve">
  <eClassifiers xsi:type="ecore:EClass" name="SystemAdaptation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyContextAction" abstract="true"
      eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetAllocationContext"
        lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetProvidingAllocationContexts"
        upperBound="-1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetRequiringAllocationContexts"
        upperBound="-1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceContainerAction" abstract="true"
      eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetResourceContainer"
        lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetLinkingResources"
        upperBound="-1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/LinkingResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeRepositoryComponentAction" eSuperTypes="#//AssemblyContextAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAllocationContext"
        lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplicateAction" eSuperTypes="#//AssemblyContextAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAllocationContext"
        lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DereplicateAction" eSuperTypes="#//AssemblyContextAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="MigrateAction" eSuperTypes="#//AssemblyContextAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAllocationContext"
        lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceProvidingAllocationContexts"
        upperBound="-1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceRequiringAllocationContexts"
        upperBound="-1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//allocation/AllocationContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllocateAction" eSuperTypes="#//ResourceContainerAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeallocateAction" eSuperTypes="#//ResourceContainerAction"/>
</ecore:EPackage>
