<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="correspondence2" nsURI="https://www.iobserve-devops.net/model/0.0.1/correspondence2"
    nsPrefix="correspondence2">
  <eClassifiers xsi:type="ecore:EClass" name="HighLevelModelElement" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//HighLevelModel"
        eOpposite="#//HighLevelModel/elements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//HighLevelModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LowLevelModelElement" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//LowLevelModel"
        eOpposite="#//LowLevelModel/elements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//LowLevelModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HighLevelModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//HighLevelModelElement" containment="true" resolveProxies="false"
        eOpposite="#//HighLevelModelElement/model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LowLevelModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1"
        upperBound="-1" eType="#//LowLevelModelElement" containment="true" resolveProxies="false"
        eOpposite="#//LowLevelModelElement/model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Correspondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" lowerBound="1" eType="#//HighLevelModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" lowerBound="1" eType="#//LowLevelModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondenceModel" eType="#//CorrespondenceModel"
        eOpposite="#//CorrespondenceModel/correspondences"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="debugStr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CorrespondenceModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="highLevelModel" lowerBound="1"
        eType="#//HighLevelModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowLevelModel" lowerBound="1"
        eType="#//LowLevelModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondences" lowerBound="1"
        upperBound="-1" eType="#//Correspondence" containment="true" resolveProxies="false"
        eOpposite="#//Correspondence/correspondenceModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity"/>
</ecore:EPackage>
