<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="privacy" nsURI="https://www.iobserve-devops.net/model/0.0.3/privacy"
    nsPrefix="privacy">
  <eClassifiers xsi:type="ecore:EClass" name="PrivacyModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceContainerLocations"
        upperBound="-1" eType="#//GeoLocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="privacyLevels" upperBound="-1"
        eType="#//IPrivacyAnnotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulatedDataSources"
        upperBound="-1" eType="#//EncapsulatedDataSource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnTypePrivacy" eSuperTypes="#//IPrivacyAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationSignature" lowerBound="1"
        eType="ecore:EClass ../../../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationSignature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPrivacyAnnotation" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" unique="false" lowerBound="1"
        eType="#//EDataPrivacyLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeoLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isocode" eType="#//EISOCode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceContainer" lowerBound="1"
        eType="ecore:EClass ../../../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterPrivacy" eSuperTypes="#//IPrivacyAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="ecore:EClass ../../../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EDataPrivacyLevel">
    <eLiterals literal="anonymous" name="ANONYMOUS"/>
    <eLiterals literal="depersonalized" value="1" name="DEPERSONALIZED"/>
    <eLiterals literal="personal" value="2" name="PERSONAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EISOCode">
    <eLiterals literal="Afghanistan" value="4" name="AFGHANISTAN"/>
    <eLiterals literal="Albania" value="8" name="ALBANIA"/>
    <eLiterals literal="Antarctica" value="10" name="ANTARCTICA"/>
    <eLiterals literal="Algeria" value="12" name="ALGERIA"/>
    <eLiterals literal="American" value="16" name="AMERICAN"/>
    <eLiterals literal="Andorra" value="20" name="ANDORRA"/>
    <eLiterals literal="Angola" value="24" name="ANGOLA"/>
    <eLiterals literal="Antigua" value="28" name="ANTIGUA"/>
    <eLiterals literal="Azerbaijan" value="31" name="AZERBAIJAN"/>
    <eLiterals literal="Argentina" value="32" name="ARGENTINA"/>
    <eLiterals literal="Australia" value="36" name="AUSTRALIA"/>
    <eLiterals literal="Austria" value="40" name="AUSTRIA"/>
    <eLiterals literal="Bahamas" value="44" name="BAHAMAS"/>
    <eLiterals literal="Bahrain" value="48" name="BAHRAIN"/>
    <eLiterals literal="Bangladesh" value="50" name="BANGLADESH"/>
    <eLiterals literal="Armenia" value="51" name="ARMENIA"/>
    <eLiterals literal="Barbados" value="52" name="BARBADOS"/>
    <eLiterals literal="Belgium" value="56" name="BELGIUM"/>
    <eLiterals literal="Bermuda" value="60" name="BERMUDA"/>
    <eLiterals literal="Bhutan" value="64" name="BHUTAN"/>
    <eLiterals literal="Bolivia" value="68" name="BOLIVIA"/>
    <eLiterals literal="Bosnia" value="70" name="BOSNIA"/>
    <eLiterals literal="Botswana" value="72" name="BOTSWANA"/>
    <eLiterals literal="Bouvet" value="74" name="BOUVET"/>
    <eLiterals literal="Brazil" value="76" name="BRAZIL"/>
    <eLiterals literal="Belize" value="84" name="BELIZE"/>
    <eLiterals literal="British Indian Ocean Territory" value="86" name="BRITISH_INDIAN_OCEAN_TERRITORY"/>
    <eLiterals literal="Solomon Islands" value="90" name="SOLOMON_ISLANDS"/>
    <eLiterals literal="Virgin Islands, UK" value="92" name="VIRGIN_ISLANDS_UK"/>
    <eLiterals literal="Brunei" value="96" name="BRUNEI"/>
    <eLiterals literal="Bulgaria" value="100" name="BULGARIA"/>
    <eLiterals literal="Myanmar" value="104" name="MYANMAR"/>
    <eLiterals literal="Burundi" value="108" name="BURUNDI"/>
    <eLiterals literal="Belarus" value="112" name="BELARUS"/>
    <eLiterals literal="Cambodia" value="116" name="CAMBODIA"/>
    <eLiterals literal="Cameroon" value="120" name="CAMEROON"/>
    <eLiterals literal="Canada" value="124" name="CANADA"/>
    <eLiterals literal="Cabo Verde" value="132" name="CABO_VERDE"/>
    <eLiterals literal="Cayman Islands" value="136" name="CAYMAN_ISLANDS"/>
    <eLiterals literal="Central African Republic" value="140" name="CENTRAL_AFRICAN_REPUBLIC"/>
    <eLiterals literal="Sri Lanka" value="144" name="SRI_LANKA"/>
    <eLiterals literal="Chad" value="148" name="CHAD"/>
    <eLiterals literal="Chile" value="152" name="CHILE"/>
    <eLiterals literal="China" value="156" name="CHINA"/>
    <eLiterals literal="Taiwan" value="158" name="TAIWAN"/>
    <eLiterals literal="Christmas Island" value="162" name="CHRISTMAS_ISLAND"/>
    <eLiterals literal="Cocos Islands" value="166" name="COCOS_ISLANDS"/>
    <eLiterals literal="Colombia" value="170" name="COLOMBIA"/>
    <eLiterals literal="Comoros" value="174" name="COMOROS"/>
    <eLiterals literal="Mayotte" value="175" name="MAYOTTE"/>
    <eLiterals literal="Congo" value="178" name="CONGO"/>
    <eLiterals literal="Democratic Republic of the Congo" value="180" name="DR_CONGO"/>
    <eLiterals literal="Cook Islands" value="184" name="COOK_ISLANDS"/>
    <eLiterals literal="Costa Rica" value="188" name="COSTA_RICA"/>
    <eLiterals literal="Croatia" value="191" name="CROATIA"/>
    <eLiterals literal="Cuba" value="192" name="CUBA"/>
    <eLiterals literal="Cyprus" value="196" name="CYPRUS"/>
    <eLiterals literal="Czechia" value="203" name="CZECHIA"/>
    <eLiterals literal="Benin" value="204" name="BENIN"/>
    <eLiterals literal="Denmark" value="208" name="DENMARK"/>
    <eLiterals literal="Dominica" value="212" name="DOMINICA"/>
    <eLiterals literal="Dominican Republic" value="214" name="DOMINICAN_REPUBLIC"/>
    <eLiterals literal="Ecuador" value="218" name="ECUADOR"/>
    <eLiterals literal="El Salvador" value="222" name="EL_SALVADOR"/>
    <eLiterals literal="Equatorial Guinea" value="226" name="EQUATORIAL_GUINEA"/>
    <eLiterals literal="Ethiopia" value="231" name="ETHIOPIA"/>
    <eLiterals literal="Eritrea" value="232" name="ERITREA"/>
    <eLiterals literal="Estonia" value="233" name="ESTONIA"/>
    <eLiterals literal="Faroe Islands" value="234" name="FAROE_ISLANDS"/>
    <eLiterals literal="Falkland Islands" value="238" name="FALKLAND_ISLANDS"/>
    <eLiterals literal="South Georgia" value="239" name="SOUTH_GEORGIA"/>
    <eLiterals literal="Fiji" value="242" name="FIJI"/>
    <eLiterals literal="Finland" value="246" name="FINLAND"/>
    <eLiterals literal="Aland" value="248" name="ALAND"/>
    <eLiterals literal="France" value="250" name="FRANCE"/>
    <eLiterals literal="French Guinea" value="254" name="FRENCH_GUINEA"/>
    <eLiterals literal="French Polinesia" value="258" name="FRENCH_POLINESIA"/>
    <eLiterals literal="French Southern Territories" value="260" name="FRENCH_SOUTHERN_TERRITORIES"/>
    <eLiterals literal="Djibouti" value="262" name="DJIBOUTI"/>
    <eLiterals literal="Gabon" value="266" name="GABON"/>
    <eLiterals literal="Georgia" value="268" name="GEORGIA"/>
    <eLiterals literal="Gambia" value="270" name="GAMBIA"/>
    <eLiterals literal="Palestine" value="275" name="PALESTINE"/>
    <eLiterals literal="Germany" value="276" name="GERMANY"/>
    <eLiterals literal="Ghana" value="288" name="GHANA"/>
    <eLiterals literal="Gibraltar" value="292" name="GIBRALTAR"/>
    <eLiterals literal="Kiribati" value="296" name="KIRIBATI"/>
    <eLiterals literal="Greece" value="300" name="GREECE"/>
    <eLiterals literal="Greenland" value="304" name="GREENLAND"/>
    <eLiterals literal="Grenada" value="308" name="GRENADA"/>
    <eLiterals literal="Guadeloupe" value="312" name="GUADELOUPE"/>
    <eLiterals literal="Guam" value="316" name="GUAM"/>
    <eLiterals literal="Guatemala" value="320" name="GUATEMALA"/>
    <eLiterals literal="Guinea" value="324" name="GUINEA"/>
    <eLiterals literal="Guyana" value="328" name="GUYANA"/>
    <eLiterals literal="Haiti" value="332" name="HAITI"/>
    <eLiterals literal="Heard Island and McDonald Islands" value="334" name="HEARD_ISLAND_AND_MC_DONALD_ISLANDS"/>
    <eLiterals literal="Holy See" value="336" name="HOLY_SEE"/>
    <eLiterals literal="Honduras" value="340" name="HONDURAS"/>
    <eLiterals literal="Hong Kong" value="344" name="HONG_KONG"/>
    <eLiterals literal="Hungary" value="348" name="HUNGARY"/>
    <eLiterals literal="Iceland" value="352" name="ICELAND"/>
    <eLiterals literal="India" value="356" name="INDIA"/>
    <eLiterals literal="Indonesia" value="360" name="INDONESIA"/>
    <eLiterals literal="Iran" value="364" name="IRAN"/>
    <eLiterals literal="Iraq" value="368" name="IRAQ"/>
    <eLiterals literal="Ireland" value="372" name="IRELAND"/>
    <eLiterals literal="Israel" value="376" name="ISRAEL"/>
    <eLiterals literal="Italy" value="380" name="ITALY"/>
    <eLiterals literal="Cote d'Ivoire" value="384" name="COTE_D_IVOIRE"/>
    <eLiterals literal="Jamaica" value="388" name="JAMAICA"/>
    <eLiterals literal="Japan" value="392" name="JAPAN"/>
    <eLiterals literal="Kazakhstan" value="398" name="KAZAKHSTAN"/>
    <eLiterals literal="Jordan" value="400" name="JORDAN"/>
    <eLiterals literal="Kenya" value="404" name="KENYA"/>
    <eLiterals literal="North korea" value="408" name="NORTH_KOREA"/>
    <eLiterals literal="South korea" value="410" name="SOUTH_KOREA"/>
    <eLiterals literal="Kuwait" value="414" name="KUWAIT"/>
    <eLiterals literal="Kyrgyzstan" value="417" name="KYRGYZSTAN"/>
    <eLiterals literal="Democratic People's Republic of Lao" value="418" name="DEMOCRATIC_PEOPLE_S_REPUBLIC_OF_LAO"/>
    <eLiterals literal="Lebanon" value="422" name="LEBANON"/>
    <eLiterals literal="Lesotho" value="426" name="LESOTHO"/>
    <eLiterals literal="Latvia" value="428" name="LATVIA"/>
    <eLiterals literal="Liberia" value="430" name="LIBERIA"/>
    <eLiterals literal="Libya" value="434" name="LIBYA"/>
    <eLiterals literal="Liechtenstein" value="438" name="LIECHTENSTEIN"/>
    <eLiterals literal="Lithuania" value="440" name="LITHUANIA"/>
    <eLiterals literal="Luxembourg" value="442" name="LUXEMBOURG"/>
    <eLiterals literal="Macao" value="446" name="MACAO"/>
    <eLiterals literal="Madagascar" value="450" name="MADAGASCAR"/>
    <eLiterals literal="Malawi" value="454" name="MALAWI"/>
    <eLiterals literal="Malaysia" value="458" name="MALAYSIA"/>
    <eLiterals literal="Maldives" value="462" name="MALDIVES"/>
    <eLiterals literal="Mali" value="466" name="MALI"/>
    <eLiterals literal="Malta" value="470" name="MALTA"/>
    <eLiterals literal="Martinique" value="474" name="MARTINIQUE"/>
    <eLiterals literal="Mauritania" value="478" name="MAURITANIA"/>
    <eLiterals literal="Mauritius" value="480" name="MAURITIUS"/>
    <eLiterals literal="Mexico" value="484" name="MEXICO"/>
    <eLiterals literal="Monaco" value="492" name="MONACO"/>
    <eLiterals literal="Mongolia" value="496" name="MONGOLIA"/>
    <eLiterals literal="Moldova" value="498" name="MOLDOVA"/>
    <eLiterals literal="Montenegro" value="499" name="MONTENEGRO"/>
    <eLiterals literal="Montserrat" value="500" name="MONTSERRAT"/>
    <eLiterals literal="Morocco" value="504" name="MOROCCO"/>
    <eLiterals literal="Mozambique" value="508" name="MOZAMBIQUE"/>
    <eLiterals literal="Oman" value="512" name="OMAN"/>
    <eLiterals literal="Namibia" value="516" name="NAMIBIA"/>
    <eLiterals literal="Nauru" value="520" name="NAURU"/>
    <eLiterals literal="Nepal" value="524" name="NEPAL"/>
    <eLiterals literal="Netherlands" value="528" name="NETHERLANDS"/>
    <eLiterals literal="Curacao" value="531" name="CURACAO"/>
    <eLiterals literal="Aruba" value="533" name="ARUBA"/>
    <eLiterals literal="Sint Maarten" value="534" name="SINT_MAARTEN"/>
    <eLiterals literal="Bonaire" value="535" name="BONAIRE"/>
    <eLiterals literal="New Caledonia" value="540" name="NEW_CALEDONIA"/>
    <eLiterals literal="Vanuatu" value="548" name="VANUATU"/>
    <eLiterals literal="New Zealand" value="554" name="NEW_ZEALAND"/>
    <eLiterals literal="Nicaragua" value="558" name="NICARAGUA"/>
    <eLiterals literal="Niger" value="562" name="NIGER"/>
    <eLiterals literal="Nigeria" value="566" name="NIGERIA"/>
    <eLiterals literal="Niue" value="570" name="NIUE"/>
    <eLiterals literal="Norfolk Island" value="574" name="NORFOLK_ISLAND"/>
    <eLiterals literal="Norway" value="578" name="NORWAY"/>
    <eLiterals literal="Northern Mariana Islands" value="580" name="NORTHERN_MARIANA_ISLANDS"/>
    <eLiterals literal="United States Minor Outlying Islands" value="581" name="UNITED_STATES_MINOR_OUTLYING_ISLANDS"/>
    <eLiterals literal="Micronesia" value="583" name="MICRONESIA"/>
    <eLiterals literal="Marshall Islands" value="584" name="MARSHALL_ISLANDS"/>
    <eLiterals literal="Palau" value="585" name="PALAU"/>
    <eLiterals literal="Pakistan" value="586" name="PAKISTAN"/>
    <eLiterals literal="Panama" value="591" name="PANAMA"/>
    <eLiterals literal="Papua" value="598" name="PAPUA"/>
    <eLiterals literal="Paraguay" value="600" name="PARAGUAY"/>
    <eLiterals literal="Peru" value="604" name="PERU"/>
    <eLiterals literal="Philippines" value="608" name="PHILIPPINES"/>
    <eLiterals literal="Pitcairn" value="612" name="PITCAIRN"/>
    <eLiterals literal="Poland" value="616" name="POLAND"/>
    <eLiterals literal="Portugal" value="620" name="PORTUGAL"/>
    <eLiterals literal="Guinea Bissau" value="624" name="GUINEA_BISSAU"/>
    <eLiterals literal="Timor Leste" value="626" name="TIMOR_LESTE"/>
    <eLiterals literal="Puerto Rico" value="630" name="PUERTO_RICO"/>
    <eLiterals literal="Qatar" value="634" name="QATAR"/>
    <eLiterals literal="Reunion" value="638" name="REUNION"/>
    <eLiterals literal="Romania" value="642" name="ROMANIA"/>
    <eLiterals literal="Russian" value="643" name="RUSSIAN"/>
    <eLiterals literal="Rwanda" value="646" name="RWANDA"/>
    <eLiterals literal="Saint Barthelemy" value="652" name="SAINT_BARTHELEMY"/>
    <eLiterals literal="Saint Helena" value="654" name="SAINT_HELENA"/>
    <eLiterals literal="Saint Kitts and Navis" value="659" name="SAINT_KITTS_AND_NAVIS"/>
    <eLiterals literal="Anguilla" value="660" name="ANGUILLA"/>
    <eLiterals literal="Saint Lucia" value="662" name="SAINT_LUCIA"/>
    <eLiterals literal="Saint Martin" value="663" name="SAINT_MARTIN"/>
    <eLiterals literal="Saint Pierre and Miquelon" value="666" name="SAINT_PIERRE"/>
    <eLiterals literal="Saint Vincent and the Grenadines" value="670" name="SAINT_VINCENT"/>
    <eLiterals literal="San Marino" value="674" name="SAN_MARINO"/>
    <eLiterals literal="Sao Tome and Principe" value="678" name="SAO_TOME"/>
    <eLiterals literal="Saudi Arabia" value="682" name="SAUDI_ARABIA"/>
    <eLiterals literal="Senegal" value="686" name="SENEGAL"/>
    <eLiterals literal="Serbia" value="688" name="SERBIA"/>
    <eLiterals literal="Seychelles" value="690" name="SEYCHELLES"/>
    <eLiterals literal="Sierra Leone" value="694" name="SIERRA_LEONE"/>
    <eLiterals literal="Singapore" value="702" name="SINGAPORE"/>
    <eLiterals literal="Slovakia" value="703" name="SLOVAKIA"/>
    <eLiterals literal="Viet Nam" value="704" name="VIETNAM"/>
    <eLiterals literal="Slovenia" value="705" name="SLOVENIA"/>
    <eLiterals literal="Somalia" value="706" name="SOMALIA"/>
    <eLiterals literal="South Africa" value="710" name="SOUTH_AFRICA"/>
    <eLiterals literal="Zimbabwe" value="716" name="ZIMBABWE"/>
    <eLiterals literal="Spain" value="724" name="SPAIN"/>
    <eLiterals literal="South Sudan" value="728" name="SOUTH_SUDAN"/>
    <eLiterals literal="Sudan" value="729" name="SUDAN"/>
    <eLiterals literal="Western Sahara" value="732" name="WESTERN_SAHARA"/>
    <eLiterals literal="Suriliteral" value="740" name="SURINAME"/>
    <eLiterals literal="Svalbard" value="744" name="SVALBARD"/>
    <eLiterals literal="Swaziland" value="748" name="SWAZILAND"/>
    <eLiterals literal="Sweden" value="752" name="SWEDEN"/>
    <eLiterals literal="Switzerland" value="756" name="SWITZERLAND"/>
    <eLiterals literal="Syrian" value="760" name="SYRIAN"/>
    <eLiterals literal="Tajikistan" value="762" name="TAJIKISTAN"/>
    <eLiterals literal="Thailand" value="764" name="THAILAND"/>
    <eLiterals literal="Togo" value="768" name="TOGO"/>
    <eLiterals literal="Tokelau" value="772" name="TOKELAU"/>
    <eLiterals literal="Tonga" value="776" name="TONGA"/>
    <eLiterals literal="Trinidad" value="780" name="TRINIDAD"/>
    <eLiterals literal="United Arab Emirates" value="784" name="UNITED_ARAB_EMIRATES"/>
    <eLiterals literal="Tunisia" value="788" name="TUNISIA"/>
    <eLiterals literal="Turkey" value="792" name="TURKEY"/>
    <eLiterals literal="Turkmenistan" value="795" name="TURKMENISTAN"/>
    <eLiterals literal="Turks Island" value="796" name="TURKS_ISLAND"/>
    <eLiterals literal="Tuvalu" value="798" name="TUVALU"/>
    <eLiterals literal="Uganda" value="800" name="UGANDA"/>
    <eLiterals literal="Ukraine" value="804" name="UKRAINE"/>
    <eLiterals literal="Macedonia" value="807" name="MACEDONIA"/>
    <eLiterals literal="Rgypt" value="818" name="EGYPT"/>
    <eLiterals literal="United Kingdom" value="826" name="UNITED_KINGDOM"/>
    <eLiterals literal="Guernsey" value="831" name="GUERNSEY"/>
    <eLiterals literal="Jersey" value="832" name="JERSEY"/>
    <eLiterals literal="Isle of Men" value="833" name="ISLE_OF_MEN"/>
    <eLiterals literal="Tanzania" value="834" name="TANZANIA"/>
    <eLiterals literal="United State of America" value="840" name="USA"/>
    <eLiterals literal="Virgin Islands, US" value="850" name="VIRGIN_ISLANDS_US"/>
    <eLiterals literal="Burkina Faso" value="854" name="BURKINA_FASO"/>
    <eLiterals literal="Uruguay" value="858" name="URUGUAY"/>
    <eLiterals literal="Uzbekistan" value="860" name="UZBEKISTAN"/>
    <eLiterals literal="Venezuela" value="862" name="VENEZUELA"/>
    <eLiterals literal="Wallis" value="876" name="WALLIS"/>
    <eLiterals literal="Samoa" value="882" name="SAMOA"/>
    <eLiterals literal="Yemen" value="887" name="YEMEN"/>
    <eLiterals literal="Zambia" value="894" name="ZAMBIA"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EncapsulatedDataSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/BasicComponent"/>
  </eClassifiers>
</ecore:EPackage>
