<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="privacy" nsURI="http://www.iobserve-devops.net/model/0.0.3/privacy"
    nsPrefix="privacy">
  <eClassifiers xsi:type="ecore:EClass" name="PrivacyModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceContainerLocations"
        upperBound="-1" eType="#//GeoLocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="privacyLevels" upperBound="-1"
        eType="#//IPrivacyAnnotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulatedDataSources"
        upperBound="-1" eType="#//EncapsulatedDataSource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnTypePrivacy" eSuperTypes="#//IPrivacyAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationSignature" lowerBound="1"
        eType="ecore:EClass ../../../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/OperationSignature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPrivacyAnnotation" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" unique="false" lowerBound="1"
        eType="#//EDataPrivacyLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeoLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isocode" eType="#//EISOCode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceContainer" lowerBound="1"
        eType="ecore:EClass ../../../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterPrivacy" eSuperTypes="#//IPrivacyAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="ecore:EClass ../../../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EDataPrivacyLevel">
    <eLiterals name="ANONYMOUS" literal="anonymous"/>
    <eLiterals name="DEPERSONALIZED" value="1" literal="depersonalized"/>
    <eLiterals name="PERSONAL" value="2" literal="personal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EISOCode">
    <eLiterals name="AFGHANISTAN" value="4" literal="Afghanistan"/>
    <eLiterals name="ALBANIA" value="8" literal="Albania"/>
    <eLiterals name="ANTARCTICA" value="10" literal="Antarctica"/>
    <eLiterals name="ALGERIA" value="12" literal="Algeria"/>
    <eLiterals name="AMERICAN" value="16" literal="American"/>
    <eLiterals name="ANDORRA" value="20" literal="Andorra"/>
    <eLiterals name="ANGOLA" value="24" literal="Angola"/>
    <eLiterals name="ANTIGUA" value="28" literal="Antigua"/>
    <eLiterals name="AZERBAIJAN" value="31" literal="Azerbaijan"/>
    <eLiterals name="ARGENTINA" value="32" literal="Argentina"/>
    <eLiterals name="AUSTRALIA" value="36" literal="Australia"/>
    <eLiterals name="AUSTRIA" value="40" literal="Austria"/>
    <eLiterals name="BAHAMAS" value="44" literal="Bahamas"/>
    <eLiterals name="BAHRAIN" value="48" literal="Bahrain"/>
    <eLiterals name="BANGLADESH" value="50" literal="Bangladesh"/>
    <eLiterals name="ARMENIA" value="51" literal="Armenia"/>
    <eLiterals name="BARBADOS" value="52" literal="Barbados"/>
    <eLiterals name="BELGIUM" value="56" literal="Belgium"/>
    <eLiterals name="BERMUDA" value="60" literal="Bermuda"/>
    <eLiterals name="BHUTAN" value="64" literal="Bhutan"/>
    <eLiterals name="BOLIVIA" value="68" literal="Bolivia"/>
    <eLiterals name="BOSNIA" value="70" literal="Bosnia"/>
    <eLiterals name="BOTSWANA" value="72" literal="Botswana"/>
    <eLiterals name="BOUVET" value="74" literal="Bouvet"/>
    <eLiterals name="BRAZIL" value="76" literal="Brazil"/>
    <eLiterals name="BELIZE" value="84" literal="Belize"/>
    <eLiterals name="BRITISH_INDIAN_OCEAN_TERRITORY" value="86" literal="British Indian Ocean Territory"/>
    <eLiterals name="SOLOMON_ISLANDS" value="90" literal="Solomon Islands"/>
    <eLiterals name="VIRGIN_ISLANDS_UK" value="92" literal="Virgin Islands, UK"/>
    <eLiterals name="BRUNEI" value="96" literal="Brunei"/>
    <eLiterals name="BULGARIA" value="100" literal="Bulgaria"/>
    <eLiterals name="MYANMAR" value="104" literal="Myanmar"/>
    <eLiterals name="BURUNDI" value="108" literal="Burundi"/>
    <eLiterals name="BELARUS" value="112" literal="Belarus"/>
    <eLiterals name="CAMBODIA" value="116" literal="Cambodia"/>
    <eLiterals name="CAMEROON" value="120" literal="Cameroon"/>
    <eLiterals name="CANADA" value="124" literal="Canada"/>
    <eLiterals name="CABO_VERDE" value="132" literal="Cabo Verde"/>
    <eLiterals name="CAYMAN_ISLANDS" value="136" literal="Cayman Islands"/>
    <eLiterals name="CENTRAL_AFRICAN_REPUBLIC" value="140" literal="Central African Republic"/>
    <eLiterals name="SRI_LANKA" value="144" literal="Sri Lanka"/>
    <eLiterals name="CHAD" value="148" literal="Chad"/>
    <eLiterals name="CHILE" value="152" literal="Chile"/>
    <eLiterals name="CHINA" value="156" literal="China"/>
    <eLiterals name="TAIWAN" value="158" literal="Taiwan"/>
    <eLiterals name="CHRISTMAS_ISLAND" value="162" literal="Christmas Island"/>
    <eLiterals name="COCOS_ISLANDS" value="166" literal="Cocos Islands"/>
    <eLiterals name="COLOMBIA" value="170" literal="Colombia"/>
    <eLiterals name="COMOROS" value="174" literal="Comoros"/>
    <eLiterals name="MAYOTTE" value="175" literal="Mayotte"/>
    <eLiterals name="CONGO" value="178" literal="Congo"/>
    <eLiterals name="DR_CONGO" value="180" literal="Democratic Republic of the Congo"/>
    <eLiterals name="COOK_ISLANDS" value="184" literal="Cook Islands"/>
    <eLiterals name="COSTA_RICA" value="188" literal="Costa Rica"/>
    <eLiterals name="CROATIA" value="191" literal="Croatia"/>
    <eLiterals name="CUBA" value="192" literal="Cuba"/>
    <eLiterals name="CYPRUS" value="196" literal="Cyprus"/>
    <eLiterals name="CZECHIA" value="203" literal="Czechia"/>
    <eLiterals name="BENIN" value="204" literal="Benin"/>
    <eLiterals name="DENMARK" value="208" literal="Denmark"/>
    <eLiterals name="DOMINICA" value="212" literal="Dominica"/>
    <eLiterals name="DOMINICAN_REPUBLIC" value="214" literal="Dominican Republic"/>
    <eLiterals name="ECUADOR" value="218" literal="Ecuador"/>
    <eLiterals name="EL_SALVADOR" value="222" literal="El Salvador"/>
    <eLiterals name="EQUATORIAL_GUINEA" value="226" literal="Equatorial Guinea"/>
    <eLiterals name="ETHIOPIA" value="231" literal="Ethiopia"/>
    <eLiterals name="ERITREA" value="232" literal="Eritrea"/>
    <eLiterals name="ESTONIA" value="233" literal="Estonia"/>
    <eLiterals name="FAROE_ISLANDS" value="234" literal="Faroe Islands"/>
    <eLiterals name="FALKLAND_ISLANDS" value="238" literal="Falkland Islands"/>
    <eLiterals name="SOUTH_GEORGIA" value="239" literal="South Georgia"/>
    <eLiterals name="FIJI" value="242" literal="Fiji"/>
    <eLiterals name="FINLAND" value="246" literal="Finland"/>
    <eLiterals name="ALAND" value="248" literal="Aland"/>
    <eLiterals name="FRANCE" value="250" literal="France"/>
    <eLiterals name="FRENCH_GUINEA" value="254" literal="French Guinea"/>
    <eLiterals name="FRENCH_POLINESIA" value="258" literal="French Polinesia"/>
    <eLiterals name="FRENCH_SOUTHERN_TERRITORIES" value="260" literal="French Southern Territories"/>
    <eLiterals name="DJIBOUTI" value="262" literal="Djibouti"/>
    <eLiterals name="GABON" value="266" literal="Gabon"/>
    <eLiterals name="GEORGIA" value="268" literal="Georgia"/>
    <eLiterals name="GAMBIA" value="270" literal="Gambia"/>
    <eLiterals name="PALESTINE" value="275" literal="Palestine"/>
    <eLiterals name="GERMANY" value="276" literal="Germany"/>
    <eLiterals name="GHANA" value="288" literal="Ghana"/>
    <eLiterals name="GIBRALTAR" value="292" literal="Gibraltar"/>
    <eLiterals name="KIRIBATI" value="296" literal="Kiribati"/>
    <eLiterals name="GREECE" value="300" literal="Greece"/>
    <eLiterals name="GREENLAND" value="304" literal="Greenland"/>
    <eLiterals name="GRENADA" value="308" literal="Grenada"/>
    <eLiterals name="GUADELOUPE" value="312" literal="Guadeloupe"/>
    <eLiterals name="GUAM" value="316" literal="Guam"/>
    <eLiterals name="GUATEMALA" value="320" literal="Guatemala"/>
    <eLiterals name="GUINEA" value="324" literal="Guinea"/>
    <eLiterals name="GUYANA" value="328" literal="Guyana"/>
    <eLiterals name="HAITI" value="332" literal="Haiti"/>
    <eLiterals name="HEARD_ISLAND_AND_MC_DONALD_ISLANDS" value="334" literal="Heard Island and McDonald Islands"/>
    <eLiterals name="HOLY_SEE" value="336" literal="Holy See"/>
    <eLiterals name="HONDURAS" value="340" literal="Honduras"/>
    <eLiterals name="HONG_KONG" value="344" literal="Hong Kong"/>
    <eLiterals name="HUNGARY" value="348" literal="Hungary"/>
    <eLiterals name="ICELAND" value="352" literal="Iceland"/>
    <eLiterals name="INDIA" value="356" literal="India"/>
    <eLiterals name="INDONESIA" value="360" literal="Indonesia"/>
    <eLiterals name="IRAN" value="364" literal="Iran"/>
    <eLiterals name="IRAQ" value="368" literal="Iraq"/>
    <eLiterals name="IRELAND" value="372" literal="Ireland"/>
    <eLiterals name="ISRAEL" value="376" literal="Israel"/>
    <eLiterals name="ITALY" value="380" literal="Italy"/>
    <eLiterals name="COTE_D_IVOIRE" value="384" literal="Cote d'Ivoire"/>
    <eLiterals name="JAMAICA" value="388" literal="Jamaica"/>
    <eLiterals name="JAPAN" value="392" literal="Japan"/>
    <eLiterals name="KAZAKHSTAN" value="398" literal="Kazakhstan"/>
    <eLiterals name="JORDAN" value="400" literal="Jordan"/>
    <eLiterals name="KENYA" value="404" literal="Kenya"/>
    <eLiterals name="NORTH_KOREA" value="408" literal="North korea"/>
    <eLiterals name="SOUTH_KOREA" value="410" literal="South korea"/>
    <eLiterals name="KUWAIT" value="414" literal="Kuwait"/>
    <eLiterals name="KYRGYZSTAN" value="417" literal="Kyrgyzstan"/>
    <eLiterals name="DEMOCRATIC_PEOPLE_S_REPUBLIC_OF_LAO" value="418" literal="Democratic People's Republic of Lao"/>
    <eLiterals name="LEBANON" value="422" literal="Lebanon"/>
    <eLiterals name="LESOTHO" value="426" literal="Lesotho"/>
    <eLiterals name="LATVIA" value="428" literal="Latvia"/>
    <eLiterals name="LIBERIA" value="430" literal="Liberia"/>
    <eLiterals name="LIBYA" value="434" literal="Libya"/>
    <eLiterals name="LIECHTENSTEIN" value="438" literal="Liechtenstein"/>
    <eLiterals name="LITHUANIA" value="440" literal="Lithuania"/>
    <eLiterals name="LUXEMBOURG" value="442" literal="Luxembourg"/>
    <eLiterals name="MACAO" value="446" literal="Macao"/>
    <eLiterals name="MADAGASCAR" value="450" literal="Madagascar"/>
    <eLiterals name="MALAWI" value="454" literal="Malawi"/>
    <eLiterals name="MALAYSIA" value="458" literal="Malaysia"/>
    <eLiterals name="MALDIVES" value="462" literal="Maldives"/>
    <eLiterals name="MALI" value="466" literal="Mali"/>
    <eLiterals name="MALTA" value="470" literal="Malta"/>
    <eLiterals name="MARTINIQUE" value="474" literal="Martinique"/>
    <eLiterals name="MAURITANIA" value="478" literal="Mauritania"/>
    <eLiterals name="MAURITIUS" value="480" literal="Mauritius"/>
    <eLiterals name="MEXICO" value="484" literal="Mexico"/>
    <eLiterals name="MONACO" value="492" literal="Monaco"/>
    <eLiterals name="MONGOLIA" value="496" literal="Mongolia"/>
    <eLiterals name="MOLDOVA" value="498" literal="Moldova"/>
    <eLiterals name="MONTENEGRO" value="499" literal="Montenegro"/>
    <eLiterals name="MONTSERRAT" value="500" literal="Montserrat"/>
    <eLiterals name="MOROCCO" value="504" literal="Morocco"/>
    <eLiterals name="MOZAMBIQUE" value="508" literal="Mozambique"/>
    <eLiterals name="OMAN" value="512" literal="Oman"/>
    <eLiterals name="NAMIBIA" value="516" literal="Namibia"/>
    <eLiterals name="NAURU" value="520" literal="Nauru"/>
    <eLiterals name="NEPAL" value="524" literal="Nepal"/>
    <eLiterals name="NETHERLANDS" value="528" literal="Netherlands"/>
    <eLiterals name="CURACAO" value="531" literal="Curacao"/>
    <eLiterals name="ARUBA" value="533" literal="Aruba"/>
    <eLiterals name="SINT_MAARTEN" value="534" literal="Sint Maarten"/>
    <eLiterals name="BONAIRE" value="535" literal="Bonaire"/>
    <eLiterals name="NEW_CALEDONIA" value="540" literal="New Caledonia"/>
    <eLiterals name="VANUATU" value="548" literal="Vanuatu"/>
    <eLiterals name="NEW_ZEALAND" value="554" literal="New Zealand"/>
    <eLiterals name="NICARAGUA" value="558" literal="Nicaragua"/>
    <eLiterals name="NIGER" value="562" literal="Niger"/>
    <eLiterals name="NIGERIA" value="566" literal="Nigeria"/>
    <eLiterals name="NIUE" value="570" literal="Niue"/>
    <eLiterals name="NORFOLK_ISLAND" value="574" literal="Norfolk Island"/>
    <eLiterals name="NORWAY" value="578" literal="Norway"/>
    <eLiterals name="NORTHERN_MARIANA_ISLANDS" value="580" literal="Northern Mariana Islands"/>
    <eLiterals name="UNITED_STATES_MINOR_OUTLYING_ISLANDS" value="581" literal="United States Minor Outlying Islands"/>
    <eLiterals name="MICRONESIA" value="583" literal="Micronesia"/>
    <eLiterals name="MARSHALL_ISLANDS" value="584" literal="Marshall Islands"/>
    <eLiterals name="PALAU" value="585" literal="Palau"/>
    <eLiterals name="PAKISTAN" value="586" literal="Pakistan"/>
    <eLiterals name="PANAMA" value="591" literal="Panama"/>
    <eLiterals name="PAPUA" value="598" literal="Papua"/>
    <eLiterals name="PARAGUAY" value="600" literal="Paraguay"/>
    <eLiterals name="PERU" value="604" literal="Peru"/>
    <eLiterals name="PHILIPPINES" value="608" literal="Philippines"/>
    <eLiterals name="PITCAIRN" value="612" literal="Pitcairn"/>
    <eLiterals name="POLAND" value="616" literal="Poland"/>
    <eLiterals name="PORTUGAL" value="620" literal="Portugal"/>
    <eLiterals name="GUINEA_BISSAU" value="624" literal="Guinea Bissau"/>
    <eLiterals name="TIMOR_LESTE" value="626" literal="Timor Leste"/>
    <eLiterals name="PUERTO_RICO" value="630" literal="Puerto Rico"/>
    <eLiterals name="QATAR" value="634" literal="Qatar"/>
    <eLiterals name="REUNION" value="638" literal="Reunion"/>
    <eLiterals name="ROMANIA" value="642" literal="Romania"/>
    <eLiterals name="RUSSIAN" value="643" literal="Russian"/>
    <eLiterals name="RWANDA" value="646" literal="Rwanda"/>
    <eLiterals name="SAINT_BARTHELEMY" value="652" literal="Saint Barthelemy"/>
    <eLiterals name="SAINT_HELENA" value="654" literal="Saint Helena"/>
    <eLiterals name="SAINT_KITTS_AND_NAVIS" value="659" literal="Saint Kitts and Navis"/>
    <eLiterals name="ANGUILLA" value="660" literal="Anguilla"/>
    <eLiterals name="SAINT_LUCIA" value="662" literal="Saint Lucia"/>
    <eLiterals name="SAINT_MARTIN" value="663" literal="Saint Martin"/>
    <eLiterals name="SAINT_PIERRE" value="666" literal="Saint Pierre and Miquelon"/>
    <eLiterals name="SAINT_VINCENT" value="670" literal="Saint Vincent and the Grenadines"/>
    <eLiterals name="SAN_MARINO" value="674" literal="San Marino"/>
    <eLiterals name="SAO_TOME" value="678" literal="Sao Tome and Principe"/>
    <eLiterals name="SAUDI_ARABIA" value="682" literal="Saudi Arabia"/>
    <eLiterals name="SENEGAL" value="686" literal="Senegal"/>
    <eLiterals name="SERBIA" value="688" literal="Serbia"/>
    <eLiterals name="SEYCHELLES" value="690" literal="Seychelles"/>
    <eLiterals name="SIERRA_LEONE" value="694" literal="Sierra Leone"/>
    <eLiterals name="SINGAPORE" value="702" literal="Singapore"/>
    <eLiterals name="SLOVAKIA" value="703" literal="Slovakia"/>
    <eLiterals name="VIETNAM" value="704" literal="Viet Nam"/>
    <eLiterals name="SLOVENIA" value="705" literal="Slovenia"/>
    <eLiterals name="SOMALIA" value="706" literal="Somalia"/>
    <eLiterals name="SOUTH_AFRICA" value="710" literal="South Africa"/>
    <eLiterals name="ZIMBABWE" value="716" literal="Zimbabwe"/>
    <eLiterals name="SPAIN" value="724" literal="Spain"/>
    <eLiterals name="SOUTH_SUDAN" value="728" literal="South Sudan"/>
    <eLiterals name="SUDAN" value="729" literal="Sudan"/>
    <eLiterals name="WESTERN_SAHARA" value="732" literal="Western Sahara"/>
    <eLiterals name="SURINAME" value="740" literal="Suriliteral"/>
    <eLiterals name="SVALBARD" value="744" literal="Svalbard"/>
    <eLiterals name="SWAZILAND" value="748" literal="Swaziland"/>
    <eLiterals name="SWEDEN" value="752" literal="Sweden"/>
    <eLiterals name="SWITZERLAND" value="756" literal="Switzerland"/>
    <eLiterals name="SYRIAN" value="760" literal="Syrian"/>
    <eLiterals name="TAJIKISTAN" value="762" literal="Tajikistan"/>
    <eLiterals name="THAILAND" value="764" literal="Thailand"/>
    <eLiterals name="TOGO" value="768" literal="Togo"/>
    <eLiterals name="TOKELAU" value="772" literal="Tokelau"/>
    <eLiterals name="TONGA" value="776" literal="Tonga"/>
    <eLiterals name="TRINIDAD" value="780" literal="Trinidad"/>
    <eLiterals name="UNITED_ARAB_EMIRATES" value="784" literal="United Arab Emirates"/>
    <eLiterals name="TUNISIA" value="788" literal="Tunisia"/>
    <eLiterals name="TURKEY" value="792" literal="Turkey"/>
    <eLiterals name="TURKMENISTAN" value="795" literal="Turkmenistan"/>
    <eLiterals name="TURKS_ISLAND" value="796" literal="Turks Island"/>
    <eLiterals name="TUVALU" value="798" literal="Tuvalu"/>
    <eLiterals name="UGANDA" value="800" literal="Uganda"/>
    <eLiterals name="UKRAINE" value="804" literal="Ukraine"/>
    <eLiterals name="MACEDONIA" value="807" literal="Macedonia"/>
    <eLiterals name="EGYPT" value="818" literal="Rgypt"/>
    <eLiterals name="UNITED_KINGDOM" value="826" literal="United Kingdom"/>
    <eLiterals name="GUERNSEY" value="831" literal="Guernsey"/>
    <eLiterals name="JERSEY" value="832" literal="Jersey"/>
    <eLiterals name="ISLE_OF_MEN" value="833" literal="Isle of Men"/>
    <eLiterals name="TANZANIA" value="834" literal="Tanzania"/>
    <eLiterals name="USA" value="840" literal="United State of America"/>
    <eLiterals name="VIRGIN_ISLANDS_US" value="850" literal="Virgin Islands, US"/>
    <eLiterals name="BURKINA_FASO" value="854" literal="Burkina Faso"/>
    <eLiterals name="URUGUAY" value="858" literal="Uruguay"/>
    <eLiterals name="UZBEKISTAN" value="860" literal="Uzbekistan"/>
    <eLiterals name="VENEZUELA" value="862" literal="Venezuela"/>
    <eLiterals name="WALLIS" value="876" literal="Wallis"/>
    <eLiterals name="SAMOA" value="882" literal="Samoa"/>
    <eLiterals name="YEMEN" value="887" literal="Yemen"/>
    <eLiterals name="ZAMBIA" value="894" literal="Zambia"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EncapsulatedDataSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../../../org.palladiosimulator.pcm/model/pcm.ecore#//repository/BasicComponent"/>
  </eClassifiers>
</ecore:EPackage>
