package org.iobserve.adaptation.droolsstages

import java.util.ArrayList
import org.iobserve.adaptation.data.AssemblyContextActionFactory
import org.iobserve.adaptation.data.graph.ComponentNode
import org.iobserve.adaptation.data.graph.DeploymentNode
import org.iobserve.adaptation.data.graph.ModelGraphRevision


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ASSEMBLY CONTEXT ACTION RULES                                                                                      //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

rule "Create replication action"
when
	$composedAdaptationActions : ArrayList()
    
    $redplNode : ComponentNode(revision == ModelGraphRevision.REDEPLOYMENT)
    
    not ComponentNode(revision == ModelGraphRevision.RUNTIME, assemblyContextID == $redplNode.getAssemblyContextID())
    
    $runtimeNode : ComponentNode(revision == ModelGraphRevision.RUNTIME, 
    		repositoryComponentID == $redplNode.getRepositoryComponentID()) 
then
	System.out.println("Found a replication!");
    $composedAdaptationActions.add(AssemblyContextActionFactory.generateReplicateAction($runtimeNode, $redplNode));
end





////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// RESOURCE CONTAINER ACTION RULES                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
