package org.iobserve.adaptation.drools

import org.iobserve.adaptation.data.AssemblyContextActionFactory

declare ListOfPersons
	listOfPersons : List
end

rule "Good Morning"
when
	person: Person(time >= 0, time < 12)
then
	person.setGreet("Good Morning " + person.getName());
	insert ( Person.test(null) );
	$listOfPersons.add( $person )
	#insert ( AssemblyContextActionFactory.generateChangeRepositoryComponentAction(null, null) );
end

rule "Good Afternoon"
when
	person: Person(time >= 12, time < 16)
then
	person.setGreet("Good Afternoon " + person.getName());
end

rule "Good Night"
when
	person: Person(time >= 16, time <= 24)
then
	person.setGreet("Good Night " + person.getName());
end