package org.iobserve.adaptation.stages

import java.util.LinkedList
import org.iobserve.adaptation.data.AssemblyContextActionFactory


rule "Good Morning"
when
	listOfPersons : LinkedList()
	person : Person(time >= 0, time < 12)
then
	person.setGreet("Good Morning " + person.getName());
	insert ( Person.test(null) );
	listOfPersons.add( person );
	// insert ( AssemblyContextActionFactory.generateChangeRepositoryComponentAction(null, null) );
end

rule "Good Afternoon"
when
	person: Person(time >= 12, time < 16)
then
	person.setGreet("Good Afternoon " + person.getName());
end

rule "Good Night"
when
	person: Person(time >= 16, time <= 24, coolness == Coolness.COOL)
then
	System.out.println(person.getName() + " is super cool");
	person.setGreet("Good Night " + person.getName());
end